deployment:
  replicaCount: 1
  appPorts:
    - name: http
      port: 3000
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 100Mi
  envs:

ingress:
  isGrpc: false
  httpBackendPort: 3000
